matrix:
  include:
     - language: node_js
       node_js:
         - 8
       cache:
         directories:
           - node_modules
       script:
         - npm run build
         - npm test
     - language: rust
       rust:
         - stable
       cache: cargo
       script:
         - cd babble-backend-src/native
         - cargo build --verbose --all
         - cargo test --verbose --all
