language: rust
rust:
  - stable
env:
  - NODE_PATH=src/utils
before_install:
  - source $HOME/.nvm/nvm.sh
  - nvm install 14.3.0
  - nvm use 14.3.0
  - node -v
  - npm -v
cache: cargo
script:
  - cd babble-backend-src/native
  - cargo test
  - cd ../../
  - npm i
  - npm run build
  - npm test -- --coverage
