language: rust
rust:
  - stable
before_install:
  - source $HOME/.nvm/nvm.sh
  - nvm install ${TRAVIS_NODE_VERSION}
  - nvm use ${TRAVIS_NODE_VERSION}
  - node -v
  - npm -v
cache: cargo
script:
  - npm i
  - npm run build
  - npm test
